[build]
  publish = "."
  command = "echo \"No build step required\""
  functions = "netlify/functions"

[functions]
  timeout = 30

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
